FogDetection/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('fogdetection_app.urls')),

]

fogdetection_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='fogdetection_app'

urlpatterns = [
      path('', views.base, name="base"),
      path('login/',views.user_login,name="login"),
      path('home/', views.home, name="home"),
      path('register/', views.register, name="register"),
      path('logout/', views.user_logout, name="logout"),

]

fogdetection_app/models.py
from django.db import models

# Create your models here.

fogdetection_app/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
import cv2
import numpy as np
from django.core.files.storage import FileSystemStorage
import os


# Create your views here.
@login_required
def home(request):
    if request.method == "POST" and request.FILES['video_file']:
        videofile = request.FILES['video_file']
        file_storage = FileSystemStorage()
        filename = file_storage.save(videofile.name, videofile)
        # video_path =file_storage.url(filename)
        video_path = os.path.join(file_storage.location, filename)
        if not os.path.exists(video_path):
            error_message = "Video file does not exist."
            return render(request, 'detection_error.html', {'error': error_message})

        cap1 = cv2.VideoCapture(video_path)
        if not cap1.isOpened():
            error_message = "Error opening video file."
            return render(request, 'detection_error.html', {'error': error_message})
        delay = 50
        fog_percentages = []
        while cap1.isOpened():
            ret, frame = cap1.read()
            if not ret:
                # return render(request,'home.html')
                break

            gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            blurred_frame = cv2.GaussianBlur(gray_frame, (15, 15), 0)
            diff = cv2.absdiff(gray_frame, blurred_frame)
            _, thresholded_diff = cv2.threshold(diff, 30, 255, cv2.THRESH_BINARY)
            white_pixel_count = np.sum(thresholded_diff == 255)

            frame_size = frame.shape[0] * frame.shape[1]
            fog_percentage = (white_pixel_count / frame_size) * 100.0
            fog_percentages.append(fog_percentage)
            cv2.putText(frame, f'Fog Percentage: {fog_percentage:.2f}%', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1,
                        (0, 0, 255), 2)
            cv2.imshow('Fog Detection', frame)
            if cv2.waitKey(delay) & 0xFF == ord('q'):
                # return render(request,'home.html')
                break

        cap1.release()
        cv2.destroyAllWindows()
        if not fog_percentages:
            error_message = "No frames processed"
            return render(request, 'detection_error.html', {'error': error_message})

        average_fog_percentage = (sum(fog_percentages) / len(fog_percentages)) * 100
        f = int(average_fog_percentage)
        return render(request, 'fogdetect.html', {'f': f})
    return render(request, 'home.html')

def base(request):
    return render(request,'base.html')

def user_login(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        user=authenticate(request,username=u,password=p)
        if user:
            login(request,user)
            return redirect('fogdetection_app:home')
        else:
            messages.error(request, "invalid user")
    return render(request,'login.html')

def register(request):
    if(request.method=="POST"):
        u =request.POST['u']
        e = request.POST['e']
        p = request.POST['p']
        cp = request.POST['cp']
        if(p==cp):
            u=User.objects.create(username=u,password=p,email=e)
            u.save()
            return redirect('fogdetection_app:login')
        else:
            messages.error(request,"PASSWORDS ARE NOT SAME")

    return render(request,'register.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('fogdetection_app:login')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
  </head>
<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background:#0000cc;">
  <div class="container-fluid">
      <a class="navbar-brand fs-4 " style="color:white;" href="#"><b>FOG DETECTOR</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <br>
      {% if user.is_authenticated %}
      <div class="d-flex nav-item ml-auto">
          <a class="btn btn-outline-light bg-dark" href="{% url 'fogdetection_app:login' %}">Logout</a></div>
    {% else %}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       <div class="d-flex nav-item" style="margin-left:920px;">
           <a class="btn btn-outline-light bg-dark"  href="{% url 'fogdetection_app:login' %}">Login</a>
        </div>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% block content %}
<center><a class="text" style="font-size:30px;" href="{% url 'fogdetection_app:login' %}"><I>Please login.......</I></a></center>
{% endblock%}
</body>
</html>

templates/detection_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/fogdetect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container-fluid">
    <h3>Average Percentage of Fog Detection:{{f}}%</h3>
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static}
{% block content %}
<div class="container-fluid" style="text-align:center;margin-top:5%;">
    <h2 style="color:blue;font-weight:bold;">FOG DECTECTION</h2>
    <br>
    <div class="border:1px solid white;bg-primary;">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name='video_file'>
        <input class="btn btn-danger" type="submit" value="Upload and Detect Fog">
    </form></div></div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
<h2>Login</h2>
<br>
  <form method="POST" action="{% url 'fogdetection_app:login' %}" enctype="multipart/form-data" class="form form-center p-2 " style="width:35%">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="Enter Username">
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter password">
    </div>
    <div class="mb-3">
        <center><input type="submit" class="btn btn-primary" value="login"></center>
    </div>
      <div>
          <a href="{% url 'fogdetection_app:register' %}" style="font-size:20px;">New User ?</a>
      </div>
  </form></div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static}
{% block content %}
<h2 style="color:red"><i>Sign Up</i></h2>
<form method="POST" action="{% url 'fogdetection_app:register' %}" class="p-2 " enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Username">
  </div>
    <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control" name="e" placeholder="Enter Email">
  </div>
    <div class="mb-3">
    <label class="form-label">password</label>
    <input type="password" class="form-control" name="p" placeholder="Enter password">
  </div>
   <div class="mb-3">
    <label class="form-label">confirm password</label>
    <input type="password" class="form-control" name="cp" placeholder="Enter password again">
 </div>
    <div class="mb-3">
    <input type="submit" class="btn btn-primary">

    </div></form>
{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
{% endblock %}